var pt_content = {
		"filter-settings": "Project artifacts: requests, tasks, requirements, etc. are mainly displayed in applications as <strong>lists</strong> or <strong>boards</strong>.<br /><br />We have already set up modules and reports for you, but you can choose to display the required <strong>columns</strong>, select the method of <strong>sorting</strong>, <strong>grouping</strong>, limit the number of rows and etc.<br /><br />Use <strong>filters</strong> to select the necessary data. There are a lot of filters and not all of them are visible on the panel, just turn on the filters you need.<br /><br /><strong>Save</strong> these settings in order to have the data displayed conveniently the next time.",
		"add-favorites": "You can quickly add a useful module to the <strong>Favorites bar</strong> in order&nbsp; to find and open it&nbsp;quickly the next time.<br /><br />You can <strong>save</strong> a configured module <strong>as a report</strong> with a new name and add it to the Favorites bar.",
		"filter-actions": "Here you will find additional features like <strong>export</strong>, <strong>import</strong>, print and others.",
		"adjust-menu-settings": "Organize <strong>comfortable</strong> workplace: move commonly used modules and reports to the \"Favorites\" panel. You can <strong>change order</strong> of menu items and <strong>group</strong> menu items using folders.<br /><br />You can customize any sections of the upper <strong>horizontal menu</strong> to better support your process. Settings can be easily repeated to the entire<strong> </strong>project <strong>team</strong>.",
		"project-settings": "To adapt the application to your needs just configure <strong>methodology</strong> options, project <strong>terminology</strong>, dictionaries, lifecycles of artifacts, add <strong>custom</strong> attributes.",
		"project-creation": "This menu allows to switch between <strong>projects</strong>, programs and portfolios.<br /><br />Projects are grouped either by programs or by portfolios, for example, all the projects which you are engaged into are grouped in the \"<strong>My Projects</strong>\" portfolio.</p><p>&nbsp;</p><p>\"<strong>All Projects</strong>\" portfolio allows to synchronize and control the activities of the company. Customization of access to this portfolio is carried out via the administrative section, in the Permissions subsection of the&nbsp;Users section.<br /><br />Create your projects with the use of the most appropriate <strong>templates</strong>.",
		"system-administration": "Creation, editing, and deleting of <strong>users</strong>, deleting of <strong>projects</strong>, configuration of common<strong> directories</strong>, for example, configuration of priorities, roles, etc., as well as whole application inspection, are carried out in the <strong>administrative section</strong>. Only the application administrators can access this section.",
		"my-tasks": "This list displays all tasks <strong>assigned</strong> to you, from all projects you are engaged into.</p><p><br />You can go to the form of a task view, change the status of the task, write off time elapsed, etc.",
		"filters": "To complete your everyday tasks use filters to display the data you need, such as your tasks <strong>assigned</strong>, requests in given <strong>states</strong> or in a particular <strong>release</strong>.<br /><br />Filter settings can be <strong>saved </strong>for the next time.",
		"state-fields": "Add an attribute and specify whether it should be displayed in the form, and whether it must be a mandatory field",
		"search-for-reports": "To <strong>find</strong> required <strong>report</strong> or <strong>module</strong> fast just start typing text. You will see correponding reports and modules you can open then.</p><p>&nbsp;</p><p>Enter <strong>artifact</strong> identifier here, e.g. I-123, to open the form with all details.",
		"setup-participants": "Here you can append project <strong>participants</strong> to give them access to the project\'s artefacts, be assignee or participate in discussions.</p><p>&nbsp;</p><p><strong>Project roles</strong> allow to <strong>restrict access</strong> to different modules or artifcats with the help of access <strong>permissions settings</strong>.",
		"bulk-actions": "<strong>Select</strong> items in list or cards on board to apply <strong>bulk actions</strong> on them, e.g. change the state, change attributes values, remove, etc.</p><p>&nbsp;</p><p>To <strong>select cards quickly</strong> just hold <strong>Ctrl</strong> button and <strong>click</strong> on cards required."
}; 